version: "3.1"

services:

  logstash:
    image: logstash:7.6.1
    volumes:
          - ./elk/logstash/:/config
    command: logstash -f /config/logstash.conf
    links:
     - elasticsearch
    depends_on:
     - elasticsearch

  elasticsearch:
     image: elasticsearch:7.6.1
     ports:
      - "9200:9200"
     volumes:
      - "./elk/es_data/es_data:/usr/share/elasticsearch/data/"
     environment:
       discovery.type: "single-node"


  kibana:
    image: kibana:7.6.1
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
     - elasticsearch

