# https://stackoverflow.com/questions/47563848/ansible-get-tag-name-and-set-hostname-over-multiple-hosts
# https://docs.ansible.com/ansible/latest/modules/ec2_remote_facts_module.html

---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Setting up setup-tools
      apt: pkg=python-setuptools state=present
    - name: Setting up pip
      apt: pkg=python-pip state=present
    - name: Installing boto3 python library using Ansible pip module
      pip:
        name: boto3
        state: present
    - ec2_instance_facts:
        region: us-east-1
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        filters:
          "tag:Name": "{{ name }}"
      register: instance_facts
    - add_host:
        name: "{{ item.tags.Name }}"
        ansible_host: "{{ item.private_ip_address }}"
        group: dev
      with_items: "{{ instance_facts.instances }}"
      loop_control:
        label: "{{ item.tags.Name }}"

# - hosts: dev
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Print Instances
      debug: 
        msg: "Instances: {{ item.tags.Name }}"
      with_items: "{{ instance_facts.instances }}"
      loop_control:
        label: "{{ item.tags.Name }}"
