---
- hosts: webservers
  gather_facts: yes
  become: true
  become_method: sudo

  tasks:
    - name: Copy Artifact
      copy:
        src: ../../../target/demo-0.0.1-SNAPSHOT.jar
        dest: /home/ubuntu/demo-0.0.1-SNAPSHOT.jar
#          owner: foo
#          group: foo
        mode: 0644
    - name: Copy Shell script
      copy:
        src: restartProcess.sh
        dest: /home/ubuntu/restartProcess.sh
        #          owner: foo
        #          group: foo
        mode: 0777
#    - name: Setting up setup-tools
#      apt: pkg=python-setuptools state=present
#    - name: Setting up pip
#      apt: pkg=python-pip state=present
#    - name: Installing lxml python library using Ansible pip module
#      pip:
#        name: lxml
#    - name: Copying Maven Artifact
#      maven_artifact:
#        group_id: junit
#        artifact_id: junit
#        version: 4.11
#        dest: /home/ubuntu/junit-4.11.jar
    - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
      shell: /home/ubuntu/restartProcess.sh >> somelog.txt
