---
- hosts: webservers
  become: true
  become_method: sudo
  vars:
    springboot_application_name: spring-boot-sample
    springboot_src_file: /home/liran/Dev/Code/Exercises/maven/jenkins/target/demo-0.0.1-SNAPSHOT.jar
    springboot_propertyfile_template: /home/liran/Dev/Code/Exercises/maven/jenkins/target/classes/application.properties
    springboot_deploy_folder: /home/ubuntu/spring-boot-demo
  roles:
    - remyma.springboot

#  roles:
#    - ansible-springboot
#    springboot_configuration_template: /path/to/your/template/spring-boot-sample.conf
